using AutoMapper;
using BookManagementSystem.Application.Dtos.Invoice;
using BookManagementSystem.Domain.Entities;

namespace BookManagementSystem.Application.Mappers
{
    public class InvoiceProfile : Profile
    {
        public InvoiceProfile()
        {
            //when map from CreateInvoiceDto to Invoice, map InvoiceDate to Date and ignore the rest
            CreateMap<CreateInvoiceDto, Invoice>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Assuming Id is generated by the database
                .ForMember(dest => dest.Date, opt => opt.MapFrom(src => 
                    string.IsNullOrEmpty(src.InvoiceDate) ? (DateOnly?)null : DateOnly.Parse(src.InvoiceDate)))
                .ForMember(dest => dest.CustomerID, opt => opt.MapFrom(src => src.CustomerID));
                

            CreateMap<Invoice, InvoiceDto>()
                .ForMember(dest => dest.InvoiceDate, opt => opt.MapFrom(src => src.Date));
            
            CreateMap<UpdateInvoiceDto, Invoice>()
                .ForMember(dest => dest.Date, opt => opt.MapFrom(src => 
                    string.IsNullOrEmpty(src.InvoiceDate) ? default : DateOnly.Parse(src.InvoiceDate)))
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));
        }
    }
}